In [25]:
list = [10, 20, 30, 40, 50]
list

[10, 20, 30, 40, 50]

In [27]:
list.append(85)
list

[10, 20, 30, 40, 50, 85]

In [29]:
list.extend([56,13,42])
list

[10, 20, 30, 40, 50, 85, 56, 13, 42]

In [31]:
list.insert(0,10)
list


[10, 10, 20, 30, 40, 50, 85, 56, 13, 42]

In [11]:
list.remove(40)
print("After remove(40):", list)

After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]


In [33]:
list.remove(30)
list

[10, 10, 20, 40, 50, 85, 56, 13, 42]

In [35]:
list.pop(6)
list

[10, 10, 20, 40, 50, 85, 13, 42]

In [39]:
list.index(85)
list

[10, 10, 20, 40, 50, 85, 13, 42]

In [41]:
list.count(2)
list

[10, 10, 20, 40, 50, 85, 13, 42]

In [43]:
list.sort()
list

[10, 10, 13, 20, 40, 42, 50, 85]

In [45]:
list.reverse()
list

[85, 50, 42, 40, 20, 13, 10, 10]

In [53]:
tuple = ("Amit", "Neha", "Rahul")
tuple

('Amit', 'Neha', 'Rahul')

In [59]:
students_list = ["Amit", "Neha", "Rahul"]
students_list[1] = "Priya"
print("Updated list:", students_list)

Updated list: ['Amit', 'Priya', 'Rahul']


In [61]:
set = {10, 20, 30, 20, 40, 10, 50}
set

{10, 20, 30, 40, 50}

In [65]:
print("Set contents:", set)

Set contents: {50, 20, 40, 10, 30}


In [67]:
person = {"name": "Amit","age": 25,"city": "Pune"}
print("Original dictionary:", person)

Original dictionary: {'name': 'Amit', 'age': 25, 'city': 'Pune'}


In [35]:
person["age"] = 26
person["email"] = "amit@example.com"
print("Updated dictionary:", person)

Updated dictionary: {'name': 'Amit', 'age': 26, 'city': 'Pune', 'email': 'amit@example.com'}


In [37]:
age = 21  
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are NOT eligible to vote. You must be at least 18 years old.")

You are eligible to vote.


In [39]:
marks = 95
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: A


In [41]:
num = 7
if num > 0:
    if num % 2 == 0:
        print(f"{num} is positive and even.")
    else:
        print(f"{num} is positive but odd.")
elif num == 0:
    print("The number is zero.")
else:
    print(f"{num} is negative.")

7 is positive but odd.


In [43]:
import numpy as np

In [45]:
scalar = np.array(5)
print("Scalar (0-D array):", scalar)

Scalar (0-D array): 5


In [47]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [49]:
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("2D Array:\n", array_2d)

2D Array:
 [[10 20 30]
 [40 50 60]]


In [51]:
import numpy as np

In [53]:
random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Array:\n", random_array)

4x4 Random Array:
 [[54 64 61 23]
 [12 94 73 30]
 [18 63 10 58]
 [67 42 84 37]]


In [79]:
import numpy as np
import pandas as pd

In [81]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
df = pd.DataFrame(array_2d, columns=["A", "B", "C"])

print("DataFrame:\n", df)


DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [59]:
import pandas as pd
import numpy as np

In [61]:
data = {
    "Name": ["Amit", "Neha", "Rahul", "Sneha", "Rohit", 
             "Anita", "Vijay", "Neha", "Kiran", "Rahul"],
    "Age": [25, 30, 28, 22, 35, 29, 40, 30, 26, 28],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Delhi", 
             "Chennai", "Mumbai", "Mumbai", "Pune", "Delhi"],
    "Salary": [50000, 60000, np.nan, 45000, 70000, 
               52000, 80000, 60000, np.nan, 70000]
}

In [63]:
df = pd.DataFrame(data)
print("Original DataFrame:\n", df, "\n")

Original DataFrame:
     Name  Age     City   Salary
0   Amit   25     Pune  50000.0
1   Neha   30   Mumbai  60000.0
2  Rahul   28    Delhi      NaN
3  Sneha   22     Pune  45000.0
4  Rohit   35    Delhi  70000.0
5  Anita   29  Chennai  52000.0
6  Vijay   40   Mumbai  80000.0
7   Neha   30   Mumbai  60000.0
8  Kiran   26     Pune      NaN
9  Rahul   28    Delhi  70000.0 



In [65]:
print("DataFrame Info:")
print(df.info(), "\n")

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None 



In [67]:
print("DataFrame Description:\n", df.describe(), "\n")

DataFrame Description:
              Age        Salary
count  10.000000      8.000000
mean   29.300000  60875.000000
std     5.100109  11849.502702
min    22.000000  45000.000000
25%    26.500000  51500.000000
50%    28.500000  60000.000000
75%    30.000000  70000.000000
max    40.000000  80000.000000 



In [69]:
print("Selected columns (Name, City):\n", df[["Name", "City"]], "\n")

Selected columns (Name, City):
     Name     City
0   Amit     Pune
1   Neha   Mumbai
2  Rahul    Delhi
3  Sneha     Pune
4  Rohit    Delhi
5  Anita  Chennai
6  Vijay   Mumbai
7   Neha   Mumbai
8  Kiran     Pune
9  Rahul    Delhi 



In [71]:
df_dropped = df.drop("City", axis=1)
print("After dropping 'City' column:\n", df_dropped, "\n")

After dropping 'City' column:
     Name  Age   Salary
0   Amit   25  50000.0
1   Neha   30  60000.0
2  Rahul   28      NaN
3  Sneha   22  45000.0
4  Rohit   35  70000.0
5  Anita   29  52000.0
6  Vijay   40  80000.0
7   Neha   30  60000.0
8  Kiran   26      NaN
9  Rahul   28  70000.0 



In [73]:
salary_mean = df["Salary"].mean()
df["Salary"].fillna(salary_mean, inplace=True)
print("After filling missing Salary with mean:\n", df, "\n")

After filling missing Salary with mean:
     Name  Age     City   Salary
0   Amit   25     Pune  50000.0
1   Neha   30   Mumbai  60000.0
2  Rahul   28    Delhi  60875.0
3  Sneha   22     Pune  45000.0
4  Rohit   35    Delhi  70000.0
5  Anita   29  Chennai  52000.0
6  Vijay   40   Mumbai  80000.0
7   Neha   30   Mumbai  60000.0
8  Kiran   26     Pune  60875.0
9  Rahul   28    Delhi  70000.0 



C:\Users\LAP\AppData\Local\Temp\ipykernel_9016\3845815481.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(salary_mean, inplace=True)


In [75]:
df_no_duplicates = df.drop_duplicates()
print("After removing duplicates:\n", df_no_duplicates)

After removing duplicates:
     Name  Age     City   Salary
0   Amit   25     Pune  50000.0
1   Neha   30   Mumbai  60000.0
2  Rahul   28    Delhi  60875.0
3  Sneha   22     Pune  45000.0
4  Rohit   35    Delhi  70000.0
5  Anita   29  Chennai  52000.0
6  Vijay   40   Mumbai  80000.0
8  Kiran   26     Pune  60875.0
9  Rahul   28    Delhi  70000.0
